'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import styles from './CaseShowcase.module.css';

type IconName = 'home' | 'globe' | 'plus' | 'search' | 'building' | 'grid' | 'scan' | 'hotel' | 'retail' | 'agentNav' | 'download' | 'heart' | 'comment' | 'chevron' | 'file' | 'undo' | 'check' | 'alert' | 'send' | 'arrowUp' | 'model' | 'tag';
const ICONS: Record<IconName, React.ReactNode> = {
  home:<><path d="M3 11.5 12 4l9 7.5"/><path d="M5.5 10v10h13V10M9.5 20v-6h5v6"/></>, globe:<><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c3 3 3 15 0 18M12 3c-3 3-3 15 0 18"/></>, plus:<path d="M12 5v14M5 12h14"/>, search:<><circle cx="10.5" cy="10.5" r="6"/><path d="m15 15 5 5"/></>, building:<><path d="M4.5 10.2h15"/><path d="M6.2 8.8 12 4.8l5.8 4"/><path d="M7 10.2v8.3M17 10.2v8.3"/><path d="M9.5 18.5v-5.4h5v5.4"/><path d="M5.2 18.5h13.6"/><path d="M8.2 7.4h7.6"/></>, grid:<><path d="M6.2 5.2h8.2l3.4 3.4v10.2H6.2z"/><path d="M14.4 5.2v3.4h3.4"/><path d="M8.7 13.1h3.2M8.7 16h2.1"/><path d="m13.1 15.3 1.7 1.7 3.4-4"/></>, scan:<><path d="M5.5 6.7 10 4.8l4.4 1.9 4.1-1.6v12.2l-4.1 1.9-4.4-1.9-4.5 1.9z"/><path d="M10 4.8v12.5M14.4 6.7v12.5"/><path d="M7.2 12.1c2.1-2.1 5.5-2.3 7.8-.5"/><path d="m13.3 9.7 1.7 1.9-2.1 1.4"/></>, hotel:<><path d="M6.4 19V5.6h7.8V19"/><path d="M14.2 10.2h3.4V19"/><path d="M8.5 8.2h.1M12 8.2h.1M8.5 11.2h.1M12 11.2h.1M8.5 14.2h.1"/><path d="M4.8 19h14.4"/><path d="m13.6 15.6 1.4 1.4 2.6-3"/></>, retail:<><path d="M6.3 9.3h11.4l-.9 9H7.2z"/><path d="M8.5 9.3V7.7a3.5 3.5 0 0 1 7 0v1.6"/><path d="M7.2 12h9.6"/><path d="m11.5 15.6 1.4 1.4 2.8-3.3"/></>, agentNav:<><rect x="6.3" y="8" width="11.4" height="8.7" rx="3"/><path d="M12 8V5.5"/><circle cx="9.8" cy="12.1" r=".8" fill="currentColor" stroke="none"/><circle cx="14.2" cy="12.1" r=".8" fill="currentColor" stroke="none"/><path d="M10.2 14.5h3.6"/><path d="M4.8 12.2h1.5M17.7 12.2h1.5"/><path d="m16.7 5.1.4-1.1.4 1.1 1.1.4-1.1.4-.4 1.1-.4-1.1-1.1-.4z"/></>, download:<><path d="M12 4v11m-4-4 4 4 4-4"/><path d="M5 19h14"/></>, heart:<path d="M12 19.2s-7.3-4.3-7.3-9.1A3.8 3.8 0 0 1 12 8.5a3.8 3.8 0 0 1 7.3 1.6c0 4.8-7.3 9.1-7.3 9.1z"/>, comment:<path d="M6.2 6.8h11.6A2.2 2.2 0 0 1 20 9v5.7a2.2 2.2 0 0 1-2.2 2.2h-4.9l-3.7 2.8v-2.8h-3A2.2 2.2 0 0 1 4 14.7V9a2.2 2.2 0 0 1 2.2-2.2z"/>, chevron:<path d="m9 5 7 7-7 7"/>, file:<><path d="M6.2 4.2h7.4l4.2 4.2v11.4H6.2z"/><path d="M13.6 4.2v4.2h4.2"/><path d="M8.7 13h6.6M8.7 15.5h4.6"/></>, undo:<><path d="m9 8-4 4 4 4"/><path d="M5 12h8a5 5 0 0 1 5 5"/></>, check:<><circle cx="12" cy="12" r="9"/><path d="m8 12 2.5 2.5L16 9"/></>, alert:<><path d="m12 3 10 18H2L12 3Z"/><path d="M12 9v5M12 17h.01"/></>, send:<path d="m4 4 17 8-17 8 4-8-4-8Zm4 8h13"/>, arrowUp:<><path d="M12 19V5"/><path d="m6 11 6-6 6 6"/></>, model:<><rect x="7" y="7" width="10" height="10"/><path d="M12 3v18M3 12h18"/></>, tag:<><path d="m3 12 9 9 9-9-9-9H3v9Z"/><circle cx="8" cy="8" r="1"/></>,
};
function Icon({name}:{name:IconName}){return <svg viewBox="0 0 24 24" aria-hidden="true">{ICONS[name]}</svg>}
const ROOT='/portfolio/system/case-showcase';
const PROJECTS=[
 {title:'故宫 | 古建智能运维',navTitle:'故宫｜古建智能运维',icon:'building' as const,meta:'3 个相关记录　最近活动 1 天前',date:'4月15日',footer:'时空状态智能认知',stats:[23,6],overview:`${ROOT}/overview/palace.avif`,detail:'/portfolio/system/cases/building-health-2560w.avif',avatar:`${ROOT}/avatars/palace.webp`,focus:'结合空间数据、传感数据和建筑构件信息，辅助理解建筑状态变化与潜在风险。',learning:'融合专业知识与数据能力，建立监测闭环。',tags:['用户需求调研','场景需求拆解','产品架构梳理','产品方案设计','低代码 Demo 搭建','产品测试验证']},
 {title:'南网 | 工程智能审查',navTitle:'南网｜工程智能审查',icon:'grid' as const,meta:'15 个相关记录　最近活动 6 天前',date:'3月18日',footer:'空间语义知识推理',stats:[107,29],overview:`${ROOT}/overview/smart-review.avif`,detail:'/portfolio/system/cases/smart-review-2560w.avif',avatar:`${ROOT}/avatars/smart-review.webp`,focus:'面向工程设计成果，将空间数据与专业审查规则连接，辅助发现设计中的冲突与风险。',learning:'把行业规则转译为可执行的产品能力，让审查过程可追踪、可复核。',tags:['行业规则梳理','审查流程拆解','空间语义建模','产品方案设计','AI 能力规划','产品测试验收']},
 {title:'南网 | 空间智能巡检',navTitle:'南网｜空间智能巡检',icon:'scan' as const,meta:'43 个相关记录　最近活动 1 天前',date:'7月3日',footer:'空间智能驱动具身协同',stats:[58,8],overview:`${ROOT}/overview/smart-inspection.avif`,detail:'/portfolio/system/cases/smart-inspection-2560w.avif',avatar:`${ROOT}/avatars/smart-inspection.webp`,focus:'结合空间模型、巡检任务与现场状态，支持设备在复杂环境中理解目标并协同执行。',learning:'以空间数据串联任务、对象和反馈，构建从感知到处置的巡检闭环。',tags:['场景需求调研','任务流程拆解','空间数据组织','Agent 工作流设计','原型 Demo 搭建','场景测试验证']},
] as const;
const TOOLS=[['toolbox-production.webp','墨斗云生产工具','@ 数据清洗与结构化'],['toolbox-data-platform.webp','墨斗云数据中台','@ 数据搭载与应用'],['toolbox-vertical-model.webp','墨斗垂类模型','@ 行业知识与专业推理'],['toolbox-agent.webp','墨斗 Agent','@ 任务理解与流程执行']] as const;

function Sidebar({active,onSelect}:{active:number;onSelect:(n:number)=>void}){const upcoming=[['亚朵｜酒店智能审查','hotel'],['盒马｜商业智能审查','retail'],['华建｜生成式 Agent','agentNav']] as const;return <aside className={styles.sidebar}><div className={styles.profile}><img src={`${ROOT}/avatars/ruby.webp`} alt=""/><strong>Ruby</strong></div><label className={styles.search}><Icon name="search"/><input type="search" placeholder="Search..."/></label><nav className={styles.sideNav} aria-label="项目案例"><p>Explore</p>{PROJECTS.map((p,i)=><button key={p.title} className={active===i?styles.selected:''} onClick={()=>onSelect(i)}><Icon name={p.icon}/><span>{p.navTitle}</span></button>)}{upcoming.map(([label,icon])=><button className={styles.upcoming} key={label} disabled><Icon name={icon}/><span>{label}</span><em>Upcoming</em></button>)}</nav><section className={styles.toolbox}><p>Toolbox</p>{TOOLS.map(([img,name,meta])=><div className={styles.tool} key={name}><img src={`${ROOT}/avatars/${img}`} alt=""/><span><strong>{name}</strong><small>{meta}</small></span><button aria-label={`下载 ${name}`}><Icon name="download"/></button></div>)}</section></aside>}
function Card({project,index,onView}:{project:(typeof PROJECTS)[number];index:number;onView:(n:number)=>void}){return <article className={styles.post}><header className={styles.author}><img src={project.avatar} alt=""/><div><strong>{project.title}</strong><p>{project.meta}<time>{project.date}</time></p></div></header><div className={styles.mediaCard}><div className={styles.preview}><img src={project.overview} alt={`${project.title}项目预览`}/><span className={styles.dots}><i/><i/><i/></span></div><footer><strong>{project.footer}</strong><button onClick={()=>onView(index)}>View</button></footer></div><div className={styles.stats}><span><Icon name="heart"/>{project.stats[0]}</span><span><Icon name="comment"/>{project.stats[1]}</span></div></article>}
function Overview({onView}:{onView:(n:number)=>void}){const track=useRef<HTMLDivElement>(null),viewport=useRef<HTMLDivElement>(null),hover=useRef(false);useEffect(()=>{const t=track.current,v=viewport.current;if(!t||!v||matchMedia('(prefers-reduced-motion: reduce)').matches)return;let d=t.scrollHeight/2,o=0,last=performance.now(),speed=d/30,frame=0;const measure=()=>{const p=d?o/d:0;d=t.scrollHeight/2;o=p*d};const ro=new ResizeObserver(measure);ro.observe(t);ro.observe(v);const tick=(now:number)=>{const dt=Math.min((now-last)/1000,.05);last=now;const target=d/(hover.current?90:30);speed+=(target-speed)*(1-Math.pow(.001,dt/.45));o=d?(o+speed*dt)%d:0;t.style.transform=`translate3d(0,${-o}px,0)`;frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>{cancelAnimationFrame(frame);ro.disconnect()}},[]);return <div ref={viewport} className={styles.feedViewport} onPointerEnter={()=>hover.current=true} onPointerLeave={()=>hover.current=false}><div ref={track} className={styles.feedTrack}>{[0,1].flatMap(copy=>PROJECTS.map((p,i)=><Card key={`${copy}-${p.title}`} project={p} index={i} onView={onView}/>))}</div></div>}
function Detail({index,onChange}:{index:number;onChange:(n:number)=>void}){const p=PROJECTS[index],move=(n:number)=>onChange((index+n+PROJECTS.length)%PROJECTS.length);return <article className={styles.detail}><div className={styles.detailIntro}><img src={p.avatar} alt=""/><div><h3>{p.title}</h3><p><strong>Focus：</strong>{p.focus}</p><p><strong>Learnings：</strong>{p.learning}</p></div></div><div className={styles.tags}>{p.tags.map(t=><span key={t}><Icon name="tag"/>{t}</span>)}</div><div className={styles.detailMedia}><button className={styles.prev} onClick={()=>move(-1)} aria-label="上一个项目"><Icon name="chevron"/></button><figure tabIndex={0}><img src={p.detail} alt={`${p.title}项目主图`}/><figcaption><strong>{p.footer}</strong><img src={p.avatar} alt=""/></figcaption></figure><button className={styles.next} onClick={()=>move(1)} aria-label="下一个项目"><Icon name="chevron"/></button></div></article>}
function Agent(){return <aside className={styles.rightRail} aria-label="AI 任务面板"><div className={styles.railHead}/><section className={styles.agent}><div className={styles.agentContent}><div className={styles.prompt}><p><b className={styles.agentCommand}>/ 审查 skills</b>调用这个 skills 帮我检查这层平面图，有没有明显问题。</p><div className={styles.promptRow}><span className={styles.attachment}><span className={styles.attachmentIcon}><Icon name="file"/></span><i className={styles.attachmentCopy}><strong>plan.dwg</strong><small>文件</small></i></span><button className={styles.agentUndo} aria-label="撤销"><Icon name="undo"/></button></div></div><p className={styles.status}>Thought 2m 21s</p><p className={styles.response}>正在解析项目数据、识别空间与构件关系，并匹配审查规则...</p><div className={styles.changes}><header><strong>Review.inspect</strong><button>Undo</button></header>{[['128 Spaces','check'],['2,436 Components','check'],['36 Rules checked','check'],['5 Issues found','alert']].map(([label,icon])=><p className={icon==='alert'?styles.issue:''} key={label}><Icon name={icon as IconName}/>{label}</p>)}</div><p className={styles.status}>Agent</p><p className={styles.response}>发现 5 项疑似问题，其中 2 项需要优先关注，已定位至对应空间与构件。</p></div><div className={styles.agentInput}><textarea aria-label="继续提问" placeholder="Add follow up..."/><footer><button className={styles.modelChip} aria-label="选择模型"><span>Modu 1.2 Atlas</span><span className={styles.modelChevron}><Icon name="chevron"/></span></button><span className={styles.agentActions}><button aria-label="发送跟进"><Icon name="send"/></button><button aria-label="添加"><Icon name="plus"/></button><button aria-label="提交"><Icon name="arrowUp"/></button></span></footer></div></section></aside>}
export default function CaseShowcase(){const[view,setView]=useState<'overview'|'details'>('overview'),[active,setActive]=useState(0);const show=useCallback((n:number)=>{setActive(n);setView('details')},[]);return <section className={styles.stage} aria-label="墨斗云项目案例"><div className={styles.window} data-view={view}><header className={styles.topbar}><span className={styles.traffic}><i/><i/><i/></span><span className={styles.topTabs}><button aria-label="首页"><Icon name="home"/></button><button className={styles.topActive} aria-label="项目社区"><Icon name="globe"/></button></span><button className={styles.topPlus} aria-label="新建"><Icon name="plus"/></button></header><div className={styles.body}><Sidebar active={active} onSelect={show}/><section className={styles.feed}><header className={styles.feedHeader}><button className={view==='overview'?styles.tabActive:''} onClick={()=>setView('overview')}>Overview</button><button className={view==='details'?styles.tabActive:''} onClick={()=>setView('details')}>Details</button></header>{view==='overview'?<Overview onView={show}/>:<Detail index={active} onChange={setActive}/>}</section>{view==='overview'&&<Agent/>}</div></div></section>}
